// frontend-solid/src/routes/PlaybookEditor.tsx
import { For, Show, createMemo, createSignal, onMount } from 'solid-js';
import { useNavigate, useParams } from '@solidjs/router';
import { getErrorMessage } from '@/api/client';
import { playbooksApi, type PlaybookFull } from '@/api/playbooks';
import { Button } from '@/components/ui/Button';
import { toast } from '@/hooks/useToast';
import { resolveActiveTeamId } from '@/utils/teamContext';
import { generateUUID } from '@/utils/uuid';

interface PlaybookFormState {
  name: string;
  description: string;
  icon: string;
  isPublic: boolean;
  createChannelOnRun: boolean;
  channelNameTemplate: string;
  keywordTriggers: string;
}

interface TaskDraft {
  id: string;
  title: string;
  description: string;
  isTemp: boolean;
}

interface ChecklistDraft {
  id: string;
  name: string;
  isTemp: boolean;
  tasks: TaskDraft[];
}

interface OriginalTaskSnapshot {
  checklistId: string;
  taskId: string;
}

function createTempChecklist(name: string): ChecklistDraft {
  return {
    id: `temp-checklist-${generateUUID()}`,
    name,
    isTemp: true,
    tasks: [],
  };
}

function createTempTask(): TaskDraft {
  return {
    id: `temp-task-${generateUUID()}`,
    title: '',
    description: '',
    isTemp: true,
  };
}

function mapPlaybookToDraft(playbook: PlaybookFull): ChecklistDraft[] {
  return playbook.checklists.map((checklist) => ({
    id: checklist.id,
    name: checklist.name,
    isTemp: false,
    tasks: checklist.tasks.map((task) => ({
      id: task.id,
      title: task.title,
      description: task.description || '',
      isTemp: false,
    })),
  }));
}

export default function PlaybookEditorRoute() {
  const navigate = useNavigate();
  const params = useParams<{ id?: string }>();
  const playbookId = () => params.id;
  const isEditing = createMemo(() => Boolean(playbookId()));

  const [teamId, setTeamId] = createSignal<string | null>(null);
  const [isLoading, setIsLoading] = createSignal(true);
  const [isSaving, setIsSaving] = createSignal(false);
  const [error, setError] = createSignal<string | null>(null);
  const [warning, setWarning] = createSignal<string | null>(null);

  const [form, setForm] = createSignal<PlaybookFormState>({
    name: '',
    description: '',
    icon: '📘',
    isPublic: false,
    createChannelOnRun: true,
    channelNameTemplate: 'run-{{date}}',
    keywordTriggers: '',
  });

  const [checklists, setChecklists] = createSignal<ChecklistDraft[]>([]);
  const [originalChecklistIds, setOriginalChecklistIds] = createSignal<string[]>([]);
  const [originalTasks, setOriginalTasks] = createSignal<OriginalTaskSnapshot[]>([]);

  const updateForm = <K extends keyof PlaybookFormState>(field: K, value: PlaybookFormState[K]) => {
    setForm((prev) => ({ ...prev, [field]: value }));
  };

  const updateChecklistName = (index: number, name: string) => {
    setChecklists((prev) =>
      prev.map((checklist, currentIndex) =>
        currentIndex === index ? { ...checklist, name } : checklist
      )
    );
  };

  const removeChecklist = (index: number) => {
    setChecklists((prev) => prev.filter((_, currentIndex) => currentIndex !== index));
  };

  const addChecklist = () => {
    setChecklists((prev) => [...prev, createTempChecklist('New Checklist')]);
  };

  const addTask = (checklistIndex: number) => {
    setChecklists((prev) =>
      prev.map((checklist, currentIndex) =>
        currentIndex === checklistIndex
          ? { ...checklist, tasks: [...checklist.tasks, createTempTask()] }
          : checklist
      )
    );
  };

  const updateTask = (
    checklistIndex: number,
    taskIndex: number,
    field: keyof Pick<TaskDraft, 'title' | 'description'>,
    value: string
  ) => {
    setChecklists((prev) =>
      prev.map((checklist, currentChecklistIndex) => {
        if (currentChecklistIndex !== checklistIndex) {
          return checklist;
        }

        return {
          ...checklist,
          tasks: checklist.tasks.map((task, currentTaskIndex) =>
            currentTaskIndex === taskIndex ? { ...task, [field]: value } : task
          ),
        };
      })
    );
  };

  const removeTask = (checklistIndex: number, taskIndex: number) => {
    setChecklists((prev) =>
      prev.map((checklist, currentIndex) =>
        currentIndex === checklistIndex
          ? {
              ...checklist,
              tasks: checklist.tasks.filter((_, currentTaskIndex) => currentTaskIndex !== taskIndex),
            }
          : checklist
      )
    );
  };

  const load = async () => {
    setIsLoading(true);
    setError(null);
    setWarning(null);

    try {
      const resolvedTeamId = await resolveActiveTeamId();
      if (!resolvedTeamId) {
        setError('No team is available yet. Join or create a team first.');
        return;
      }
      setTeamId(resolvedTeamId);

      if (!isEditing()) {
        setChecklists([createTempChecklist('Default Checklist')]);
        return;
      }

      const currentPlaybookId = playbookId();
      if (!currentPlaybookId) {
        setError('Invalid playbook id.');
        return;
      }

      const playbook = await playbooksApi.get(currentPlaybookId);

      setForm({
        name: playbook.name,
        description: playbook.description || '',
        icon: playbook.icon || '📘',
        isPublic: playbook.is_public,
        createChannelOnRun: playbook.create_channel_on_run,
        channelNameTemplate: playbook.channel_name_template || 'run-{{date}}',
        keywordTriggers: playbook.keyword_triggers?.join(', ') || '',
      });

      const checklistDrafts = mapPlaybookToDraft(playbook);
      setChecklists(checklistDrafts.length > 0 ? checklistDrafts : [createTempChecklist('Default Checklist')]);
      setOriginalChecklistIds(playbook.checklists.map((checklist) => checklist.id));
      setOriginalTasks(
        playbook.checklists.flatMap((checklist) =>
          checklist.tasks.map((task) => ({
            checklistId: checklist.id,
            taskId: task.id,
          }))
        )
      );
    } catch (err) {
      setError(getErrorMessage(err) || 'Failed to load playbook.');
    } finally {
      setIsLoading(false);
    }
  };

  const syncChecklists = async (savedPlaybookId: string) => {
    const drafts = checklists();
    const keptChecklistIds = new Set<string>();
    const keptTaskIds = new Set<string>();
    const checklistIdMap = new Map<string, string>();
    let checklistRenameSkipped = false;

    for (let checklistIndex = 0; checklistIndex < drafts.length; checklistIndex += 1) {
      const checklist = drafts[checklistIndex];
      const checklistName = checklist.name.trim() || `Checklist ${checklistIndex + 1}`;
      const sortOrder = checklistIndex + 1;

      let persistedChecklistId = checklist.id;
      if (checklist.isTemp) {
        const createdChecklist = await playbooksApi.createChecklist(savedPlaybookId, {
          name: checklistName,
          sort_order: sortOrder,
        });
        persistedChecklistId = createdChecklist.id;
        checklistIdMap.set(checklist.id, persistedChecklistId);
      } else {
        keptChecklistIds.add(checklist.id);
        if (checklist.name.trim() !== checklistName) {
          checklistRenameSkipped = true;
        }
      }

      for (let taskIndex = 0; taskIndex < checklist.tasks.length; taskIndex += 1) {
        const task = checklist.tasks[taskIndex];
        const title = task.title.trim();
        if (!title) {
          continue;
        }

        const description = task.description.trim();
        const payload = {
          title,
          description: description || null,
          sort_order: taskIndex + 1,
        };

        if (task.isTemp) {
          const createdTask = await playbooksApi.createTask(persistedChecklistId, payload);
          keptTaskIds.add(createdTask.id);
        } else {
          const updatedTask = await playbooksApi.updateTask(task.id, payload);
          keptTaskIds.add(updatedTask.id);
        }
      }
    }

    const tasksGroupedByChecklist = originalTasks().reduce<Record<string, string[]>>((acc, item) => {
      acc[item.checklistId] = acc[item.checklistId] || [];
      acc[item.checklistId].push(item.taskId);
      return acc;
    }, {});

    for (const checklistId of originalChecklistIds()) {
      if (!keptChecklistIds.has(checklistId)) {
        await playbooksApi.deleteChecklist(savedPlaybookId, checklistId);
        continue;
      }

      const checklistTaskIds = tasksGroupedByChecklist[checklistId] || [];
      for (const taskId of checklistTaskIds) {
        if (!keptTaskIds.has(taskId)) {
          await playbooksApi.deleteTask(taskId);
        }
      }
    }

    if (checklistRenameSkipped || checklistIdMap.size > 0) {
      setWarning(
        checklistRenameSkipped
          ? 'Existing checklist names cannot be updated by current API. New checklists and tasks were saved.'
          : null
      );
    }
  };

  const save = async () => {
    const currentTeamId = teamId();
    if (!currentTeamId) {
      setError('No team is available yet.');
      return;
    }

    const payload = form();
    if (!payload.name.trim()) {
      setError('Playbook name is required.');
      return;
    }

    if (checklists().length === 0) {
      setError('Add at least one checklist before saving.');
      return;
    }

    setIsSaving(true);
    setError(null);
    setWarning(null);

    try {
      const keywordTriggers = payload.keywordTriggers
        .split(',')
        .map((keyword) => keyword.trim())
        .filter(Boolean);

      const playbookPayload = {
        name: payload.name.trim(),
        description: payload.description.trim() || undefined,
        icon: payload.icon.trim() || undefined,
        is_public: payload.isPublic,
        create_channel_on_run: payload.createChannelOnRun,
        channel_name_template: payload.createChannelOnRun
          ? payload.channelNameTemplate.trim() || 'run-{{date}}'
          : undefined,
        keyword_triggers: keywordTriggers,
      };

      let savedPlaybookId = playbookId();
      if (savedPlaybookId) {
        await playbooksApi.update(savedPlaybookId, playbookPayload);
      } else {
        const created = await playbooksApi.create(currentTeamId, playbookPayload);
        savedPlaybookId = created.id;
      }

      if (!savedPlaybookId) {
        throw new Error('Playbook id is missing after save.');
      }

      await syncChecklists(savedPlaybookId);
      toast.success('Playbook saved', 'Your changes were stored successfully.');
      navigate('/playbooks');
    } catch (err) {
      const message = getErrorMessage(err) || 'Failed to save playbook.';
      setError(message);
      toast.error('Unable to save playbook', message);
    } finally {
      setIsSaving(false);
    }
  };

  onMount(() => {
    void load();
  });

  return (
    <div class="h-full flex flex-col bg-bg-app">
      <header class="border-b border-border-1 bg-bg-surface-1 px-6 py-4 flex items-center justify-between">
        <div class="flex items-center gap-3">
          <Button variant="ghost" size="sm" onClick={() => navigate('/playbooks')}>
            Back
          </Button>
          <div>
            <h1 class="text-xl font-semibold text-text-1">
              {isEditing() ? 'Edit Playbook' : 'Create Playbook'}
            </h1>
            <p class="text-sm text-text-3">
              Configure automation settings, checklists, and run tasks.
            </p>
          </div>
        </div>
        <Button variant="primary" loading={isSaving()} onClick={() => void save()}>
          Save Playbook
        </Button>
      </header>

      <main class="flex-1 overflow-y-auto p-6">
        <Show
          when={!isLoading()}
          fallback={
            <div class="h-full flex items-center justify-center">
              <div class="w-10 h-10 rounded-full border-4 border-brand/20 border-t-brand animate-spin" />
            </div>
          }
        >
          <div class="mx-auto w-full max-w-4xl space-y-6">
            <Show when={error()}>
              <div class="rounded-xl border border-danger/30 bg-danger/10 px-4 py-3 text-sm text-danger">
                {error()}
              </div>
            </Show>

            <Show when={warning()}>
              <div class="rounded-xl border border-warning/30 bg-warning/10 px-4 py-3 text-sm text-warning">
                {warning()}
              </div>
            </Show>

            <section class="rounded-xl border border-border-1 bg-bg-surface-1 p-5 space-y-4">
              <h2 class="text-lg font-semibold text-text-1">General Information</h2>
              <div class="grid grid-cols-1 md:grid-cols-[84px_1fr] gap-4">
                <label class="space-y-1">
                  <span class="text-sm font-medium text-text-2">Icon</span>
                  <input
                    type="text"
                    value={form().icon}
                    onInput={(event) => updateForm('icon', event.currentTarget.value)}
                    class="w-full rounded-lg border border-border-1 bg-bg-app px-3 py-2 text-center text-2xl text-text-1"
                  />
                </label>
                <label class="space-y-1">
                  <span class="text-sm font-medium text-text-2">Name</span>
                  <input
                    type="text"
                    value={form().name}
                    onInput={(event) => updateForm('name', event.currentTarget.value)}
                    placeholder="Incident Response"
                    class="w-full rounded-lg border border-border-1 bg-bg-app px-3 py-2 text-sm text-text-1"
                  />
                </label>
              </div>
              <label class="space-y-1 block">
                <span class="text-sm font-medium text-text-2">Description</span>
                <textarea
                  value={form().description}
                  onInput={(event) => updateForm('description', event.currentTarget.value)}
                  rows={3}
                  class="w-full rounded-lg border border-border-1 bg-bg-app px-3 py-2 text-sm text-text-1 resize-y"
                />
              </label>
            </section>

            <section class="rounded-xl border border-border-1 bg-bg-surface-1 p-5 space-y-4">
              <h2 class="text-lg font-semibold text-text-1">Automation</h2>

              <label class="inline-flex items-center gap-2 text-sm text-text-2">
                <input
                  type="checkbox"
                  checked={form().isPublic}
                  onChange={(event) => updateForm('isPublic', event.currentTarget.checked)}
                  class="h-4 w-4 rounded border-border-2"
                />
                Public in team
              </label>

              <label class="inline-flex items-center gap-2 text-sm text-text-2">
                <input
                  type="checkbox"
                  checked={form().createChannelOnRun}
                  onChange={(event) =>
                    updateForm('createChannelOnRun', event.currentTarget.checked)
                  }
                  class="h-4 w-4 rounded border-border-2"
                />
                Create channel when run starts
              </label>

              <Show when={form().createChannelOnRun}>
                <label class="space-y-1 block">
                  <span class="text-sm font-medium text-text-2">Channel Name Template</span>
                  <input
                    type="text"
                    value={form().channelNameTemplate}
                    onInput={(event) =>
                      updateForm('channelNameTemplate', event.currentTarget.value)
                    }
                    placeholder="run-{{date}}"
                    class="w-full rounded-lg border border-border-1 bg-bg-app px-3 py-2 text-sm text-text-1"
                  />
                  <p class="text-xs text-text-3">Supported variables: {'{{date}}, {{playbook_name}}'}</p>
                </label>
              </Show>

              <label class="space-y-1 block">
                <span class="text-sm font-medium text-text-2">Keyword Triggers</span>
                <input
                  type="text"
                  value={form().keywordTriggers}
                  onInput={(event) => updateForm('keywordTriggers', event.currentTarget.value)}
                  placeholder="incident, outage, escalation"
                  class="w-full rounded-lg border border-border-1 bg-bg-app px-3 py-2 text-sm text-text-1"
                />
                <p class="text-xs text-text-3">
                  Comma-separated keywords that can trigger this playbook.
                </p>
              </label>
            </section>

            <section class="rounded-xl border border-border-1 bg-bg-surface-1 p-5 space-y-4">
              <div class="flex items-center justify-between gap-3">
                <h2 class="text-lg font-semibold text-text-1">Checklists & Tasks</h2>
                <Button variant="secondary" size="sm" onClick={addChecklist}>
                  Add Checklist
                </Button>
              </div>

              <div class="space-y-4">
                <For each={checklists()}>
                  {(checklist, checklistIndex) => (
                    <article class="rounded-xl border border-border-1 bg-bg-app p-4 space-y-3">
                      <div class="flex items-center gap-2">
                        <input
                          type="text"
                          value={checklist.name}
                          onInput={(event) =>
                            updateChecklistName(checklistIndex(), event.currentTarget.value)
                          }
                          disabled={!checklist.isTemp}
                          class="flex-1 rounded-lg border border-border-1 bg-bg-surface-1 px-3 py-2 text-sm text-text-1 disabled:opacity-70 disabled:cursor-not-allowed"
                          placeholder="Checklist name"
                        />
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => removeChecklist(checklistIndex())}
                        >
                          Remove
                        </Button>
                      </div>

                      <Show when={!checklist.isTemp}>
                        <p class="text-xs text-text-3">
                          Checklist rename is not available in the current API; add a new checklist
                          if you need a different name.
                        </p>
                      </Show>

                      <div class="space-y-2">
                        <For each={checklist.tasks}>
                          {(task, taskIndex) => (
                            <div class="rounded-lg border border-border-1 bg-bg-surface-1 p-3 space-y-2">
                              <div class="flex gap-2">
                                <input
                                  type="text"
                                  value={task.title}
                                  onInput={(event) =>
                                    updateTask(
                                      checklistIndex(),
                                      taskIndex(),
                                      'title',
                                      event.currentTarget.value
                                    )
                                  }
                                  placeholder="Task title"
                                  class="flex-1 rounded-lg border border-border-1 bg-bg-app px-3 py-2 text-sm text-text-1"
                                />
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => removeTask(checklistIndex(), taskIndex())}
                                >
                                  Delete
                                </Button>
                              </div>
                              <input
                                type="text"
                                value={task.description}
                                onInput={(event) =>
                                  updateTask(
                                    checklistIndex(),
                                    taskIndex(),
                                    'description',
                                    event.currentTarget.value
                                  )
                                }
                                placeholder="Description (optional)"
                                class="w-full rounded-lg border border-border-1 bg-bg-app px-3 py-2 text-sm text-text-1"
                              />
                            </div>
                          )}
                        </For>
                      </div>

                      <Button
                        variant="secondary"
                        size="sm"
                        onClick={() => addTask(checklistIndex())}
                      >
                        Add Task
                      </Button>
                    </article>
                  )}
                </For>
              </div>
            </section>
          </div>
        </Show>
      </main>
    </div>
  );
}

// archive/frontend-vue-backup/src/components/playbooks/PlaybookEditor.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { Plus, Trash2, GripVertical, CheckSquare, Save, ArrowLeft, X } from 'lucide-vue-next'
import { usePlaybookStore } from '../../stores/playbooks'
import BaseButton from '../atomic/BaseButton.vue'
import { useToast } from '../../composables/useToast'
import { type ChecklistWithTasks, playbooksApi } from '../../api/playbooks'

const router = useRouter()
const route = useRoute()
const playbookStore = usePlaybookStore()
const toast = useToast()

const props = defineProps<{
    id?: string // If present, editing existing playbook
}>()

const loading = ref(false)
const saving = ref(false)

const form = ref({
    name: '',
    description: '',
    icon: '📘',
    is_public: false,
    create_channel_on_run: true,
    channel_name_template: 'incident-{{date}}',
    keyword_triggers: '',
})

const checklists = ref<ChecklistWithTasks[]>([])

const isEditing = computed(() => !!props.id || !!route.params.id)

onMounted(async () => {
    const playbookId = (props.id || route.params.id) as string
    if (playbookId) {
        loading.value = true
        try {
            await playbookStore.fetchPlaybook(playbookId)
            const playbook = playbookStore.currentPlaybook
            if (playbook) {
                form.value = {
                    name: playbook.name,
                    description: playbook.description || '',
                    icon: playbook.icon || '📘',
                    is_public: playbook.is_public,
                    create_channel_on_run: playbook.create_channel_on_run,
                    channel_name_template: playbook.channel_name_template || '',
                    keyword_triggers: playbook.keyword_triggers?.join(', ') || '',
                }
                checklists.value = JSON.parse(JSON.stringify(playbook.checklists))
            }
        } catch (e) {
            toast.error('Error', 'Failed to load playbook')
        } finally {
            loading.value = false
        }
    } else {
        // Add default checklist for new playbook
        checklists.value = [{
            id: 'temp-1',
            playbook_id: '',
            name: 'Default Checklist',
            sort_order: 1,
            created_at: new Date().toISOString(),
            tasks: []
        }]
    }
})

function addChecklist() {
    checklists.value.push({
        id: `temp-${Date.now()}`,
        playbook_id: '',
        name: 'New Checklist',
        sort_order: checklists.value.length + 1,
        created_at: new Date().toISOString(),
        tasks: []
    })
}

function removeChecklist(index: number) {
    if (checklists.value[index]) {
        checklists.value.splice(index, 1)
    }
}

function addTask(checklistIndex: number) {
    const checklist = checklists.value[checklistIndex]
    if (checklist) {
        checklist.tasks.push({
            id: `temp-task-${Date.now()}`,
            checklist_id: checklist.id,
            title: '',
            description: '',
            default_assignee_id: null,
            assignee_role: null,
            due_after_minutes: null,
            slash_command: null,
            webhook_url: null,
            sort_order: checklist.tasks.length + 1,
            created_at: new Date().toISOString()
        })
    }
}

function removeTask(checklistIndex: number, taskIndex: number) {
    const checklist = checklists.value[checklistIndex]
    if (checklist && checklist.tasks[taskIndex]) {
        checklist.tasks.splice(taskIndex, 1)
    }
}

async function save() {
    if (!form.value.name) {
        toast.error('Validation error', 'Playbook name is required')
        return
    }

    saving.value = true
    try {
        let playbookId = props.id || route.params.id as string
        
        const payload = {
            ...form.value,
            keyword_triggers: form.value.keyword_triggers.split(',').map(s => s.trim()).filter(s => s.length > 0)
        }
        
        // 1. Create or Update Playbook
        if (isEditing.value) {
            await playbookStore.updatePlaybook(playbookId, payload)
        } else {
            const newPlaybook = await playbookStore.createPlaybook(payload)
            if (newPlaybook) {
                playbookId = newPlaybook.id
            }
        }

        // 2. Sync Checklists and Tasks
        // We iterate through checklists and create them if they have temp IDs
        // For tasks, we do the same
        if (playbookId) {
            // Simplified sync logic for MVP - just create new checklists/tasks that are temp
            // Real implementation would need proper diffing/updating
            for (const checklist of checklists.value) {
                if (checklist.id.startsWith('temp-')) {
                    const newChecklist = await playbooksApi.createChecklist(playbookId, {
                        name: checklist.name,
                        sort_order: checklist.sort_order
                    })
                    // Create tasks for this new checklist
                    for (const task of checklist.tasks) {
                        await playbooksApi.createTask(newChecklist.data.id, {
                            title: task.title,
                            description: task.description,
                            sort_order: task.sort_order
                        })
                    }
                } else {
                    // Existing checklist, check for new tasks
                    for (const task of checklist.tasks) {
                        if (task.id.startsWith('temp-')) {
                            await playbooksApi.createTask(checklist.id, {
                                title: task.title,
                                description: task.description,
                                sort_order: task.sort_order
                            })
                        }
                    }
                }
            }
        }
        
        toast.success('Saved', 'Playbook saved successfully')
        router.push('/playbooks')
    } catch (e: any) {
        toast.error('Error', e.message || 'Failed to save playbook')
    } finally {
        saving.value = false
    }
}
</script>

<template>
    <div class="h-full flex flex-col bg-gray-50 dark:bg-gray-900">
        <!-- Header -->
        <header class="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 px-6 py-4 flex justify-between items-center">
            <div class="flex items-center space-x-4">
                <button @click="router.back()" class="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg">
                    <ArrowLeft class="w-5 h-5 text-gray-500" />
                </button>
                <div>
                    <h1 class="text-xl font-bold text-gray-900 dark:text-white">
                        {{ isEditing ? 'Edit Playbook' : 'Create Playbook' }}
                    </h1>
                </div>
            </div>
            <BaseButton @click="save" :loading="saving">
                <Save class="w-4 h-4 mr-2" />
                Save Playbook
            </BaseButton>
        </header>

        <!-- Content -->
        <div class="flex-1 overflow-y-auto p-6 max-w-4xl mx-auto w-full">
            <div class="space-y-8">
                <!-- General Settings -->
                <section class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6 shadow-sm">
                    <h2 class="text-lg font-semibold mb-4 text-gray-900 dark:text-white">General Information</h2>
                    <div class="space-y-4">
                        <div class="flex space-x-4">
                            <div class="w-20">
                                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Icon</label>
                                <input v-model="form.icon" class="w-full text-center text-2xl px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white" />
                            </div>
                            <div class="flex-1">
                                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Name</label>
                                <input v-model="form.name" type="text" placeholder="e.g. Incident Response" class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white" />
                            </div>
                        </div>
                        <div>
                            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Description</label>
                            <textarea v-model="form.description" rows="2" class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"></textarea>
                        </div>
                    </div>
                </section>

                <!-- Automation Settings -->
                <section class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6 shadow-sm">
                    <h2 class="text-lg font-semibold mb-4 text-gray-900 dark:text-white">Automation & Settings</h2>
                    <div class="space-y-4">
                        <div class="flex items-center space-x-2">
                            <input v-model="form.is_public" type="checkbox" id="is_public" class="rounded border-gray-300 text-primary focus:ring-primary" />
                            <label for="is_public" class="text-sm font-medium text-gray-700 dark:text-gray-300">Public (visible to everyone in team)</label>
                        </div>

                        <div class="border-t border-gray-200 dark:border-gray-700 pt-4">
                            <div class="flex items-center space-x-2 mb-2">
                                <input v-model="form.create_channel_on_run" type="checkbox" id="create_channel" class="rounded border-gray-300 text-primary focus:ring-primary" />
                                <label for="create_channel" class="text-sm font-medium text-gray-700 dark:text-gray-300">Create new channel on run</label>
                            </div>
                            
                            <div v-if="form.create_channel_on_run" class="ml-6">
                                <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Channel Name Template</label>
                                <input v-model="form.channel_name_template" type="text" placeholder="incident-{{date}}" class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white" />
                                <p class="text-xs text-gray-500 mt-1" v-pre>Available variables: {{date}}, {{playbook_name}}</p>
                            </div>
                        </div>

                        <div class="border-t border-gray-200 dark:border-gray-700 pt-4">
                            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Keyword Triggers</label>
                            <input v-model="form.keyword_triggers" type="text" placeholder="e.g. incident, outage, server down" class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white" />
                            <p class="text-xs text-gray-500 mt-1">Comma separated keywords that will trigger a prompt to start this playbook.</p>
                        </div>
                    </div>
                </section>

                <!-- Checklists & Tasks -->
                <section class="space-y-6">
                    <div class="flex items-center justify-between">
                        <h2 class="text-lg font-semibold text-gray-900 dark:text-white">Checklists & Tasks</h2>
                        <BaseButton variant="secondary" size="sm" @click="addChecklist">
                            <Plus class="w-4 h-4 mr-2" />
                            Add Checklist
                        </BaseButton>
                    </div>

                    <div v-for="(checklist, cIndex) in checklists" :key="checklist.id" 
                         class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden shadow-sm">
                        <!-- Checklist Header -->
                        <div class="bg-gray-50 dark:bg-gray-700/50 p-4 flex items-center space-x-3 border-b border-gray-200 dark:border-gray-700">
                            <GripVertical class="w-5 h-5 text-gray-400 cursor-move" />
                            <input v-model="checklist.name" class="flex-1 bg-transparent font-medium text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary rounded px-2" placeholder="Checklist Name" />
                            <button @click="removeChecklist(cIndex)" class="text-gray-400 hover:text-red-500">
                                <Trash2 class="w-4 h-4" />
                            </button>
                        </div>

                        <!-- Tasks -->
                        <div class="p-4 space-y-2">
                            <div v-for="(task, tIndex) in checklist.tasks" :key="task.id" class="flex items-start space-x-3 group">
                                <CheckSquare class="w-5 h-5 text-gray-400 mt-2" />
                                <div class="flex-1 space-y-1">
                                    <input v-model="task.title" class="w-full bg-transparent border-b border-transparent hover:border-gray-200 dark:hover:border-gray-600 focus:border-primary focus:outline-none py-1 text-gray-900 dark:text-white" placeholder="Task title..." />
                                    <input v-model="task.description" class="w-full text-sm bg-transparent border-none focus:ring-0 p-0 text-gray-500" placeholder="Description (optional)" />
                                </div>
                                <button @click="removeTask(cIndex, tIndex)" class="opacity-0 group-hover:opacity-100 text-gray-400 hover:text-red-500 p-1">
                                    <X class="w-4 h-4" />
                                </button>
                            </div>
                            
                            <button @click="addTask(cIndex)" class="flex items-center text-sm text-gray-500 hover:text-primary mt-2 px-1">
                                <Plus class="w-4 h-4 mr-1" />
                                Add Task
                            </button>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</template>
